#!/usr/bin/env python3
"""Publish a rendered carousel story to Instagram (as a carousel post) and/or a
Facebook Page (as a multi-photo post), via the Meta Graph API.

Requires three values in .env (see the setup guide for how to get them):
  META_PAGE_ACCESS_TOKEN  - a long-lived Facebook Page access token
  META_PAGE_ID            - the Facebook Page's numeric ID
  META_IG_USER_ID         - the Instagram Business/Creator account ID linked to that Page

The Graph API must be able to fetch each slide image over the public internet (a
local file path is not enough), so the caller supplies a currently-reachable
`base_url` (e.g. a Cloudflare tunnel URL) at publish time rather than a hardcoded
value, since a quick-tunnel URL changes every time it's restarted.
"""
import json
import os
import re
from pathlib import Path

import requests
from dotenv import load_dotenv

HERE = Path(__file__).parent
load_dotenv(HERE.parent / ".env", override=True)

DATA_DIR = Path(os.environ.get("DATA_DIR", str(HERE)))
CONTENT_DIR = DATA_DIR / "content"
CODE_OUT = DATA_DIR / "assets" / "code_pilot"
GRAPH_VERSION = "v21.0"
GRAPH_URL = f"https://graph.facebook.com/{GRAPH_VERSION}"

PAGE_ACCESS_TOKEN = os.environ.get("META_PAGE_ACCESS_TOKEN")
PAGE_ID = os.environ.get("META_PAGE_ID")
IG_USER_ID = os.environ.get("META_IG_USER_ID")

SLIDE_KINDS = ("cover", "backstory", "news", "why", "engage")


def credentials_status():
    return {
        "instagram": bool(PAGE_ACCESS_TOKEN and IG_USER_ID),
        "facebook": bool(PAGE_ACCESS_TOKEN and PAGE_ID),
    }


def strip_markup(text):
    return re.sub(r"\*\*(.+?)\*\*", r"\1", text or "")


def _normalize_title(t):
    return re.sub(r"[^a-z0-9]+", "", (t or "").lower())


def find_content_json(slug, title=None):
    """Locate the content JSON for a story. Stories generated by new_post.py use the
    same slug for both the content JSON filename and the image output folder, so the
    fast path just globs on slug. But the site's original 25 carousels were rendered
    with short, hand-picked image-folder slugs (e.g. "apple-nvidia") that don't match
    their content JSON's full slugify(title) filename (e.g. "apple-unseats-nvidia-to-
    become-world-s-most-valuable-company") -- so for those we fall back to matching by
    the story's title, which the frontend already has on hand in the DOM.
    """
    matches = list(CONTENT_DIR.glob(f"content_*_{slug}.json"))
    if matches:
        matches.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        return json.loads(matches[0].read_text())

    if title:
        target = _normalize_title(title)
        for p in CONTENT_DIR.glob("content_*.json"):
            try:
                data = json.loads(p.read_text())
            except (json.JSONDecodeError, OSError):
                continue
            if _normalize_title(data.get("source_item", {}).get("title")) == target:
                return data

    raise FileNotFoundError(f"no content JSON found for slug '{slug}'")


def build_caption(data):
    """Generic single caption, used as the fallback for stories generated before the
    per-platform DISTRIBUTION fields existed (see generate_content.py). Every new story
    gets four real, platform-native captions instead -- see build_platform_captions."""
    s = data["slides"]
    # New schema (variable beat count): {"hook":..., "beats":[...], "engage":...}.
    # Old schema (fixed 5 slides, still present in already-generated stories):
    # {"slide1_hook":..., "slide2_backstory":..., ..., "slide5_engage":...}.
    hook, engage = (s["hook"], s["engage"]) if "hook" in s else (s["slide1_hook"], s["slide5_engage"])
    lines = [strip_markup(hook["label"])]
    if hook.get("subhead"):
        lines.append(hook["subhead"])
    lines.append("")
    lines.append(strip_markup(engage["headline"]))
    if engage.get("cta"):
        lines.append(engage["cta"])
    lines.append("")
    lines.append("Follow for daily business stories that matter to India.")
    lines.append("#India #Business #StartupNews #Markets")
    return "\n".join(lines)


PLATFORMS = ("instagram", "facebook", "linkedin", "twitter")


def _combine_caption_and_hashtags(caption, hashtags):
    caption = (caption or "").strip()
    tags = " ".join(f"#{h.lstrip('#')}" for h in (hashtags or []) if h and h.strip())
    if not tags:
        return caption
    return f"{caption}\n\n{tags}"


def build_platform_captions(data):
    """One ready-to-paste caption+hashtags string per platform. Uses the story's own
    DISTRIBUTION field (written per-platform by generate_content.py, applying real
    algorithm/psychology differences between Instagram, Facebook, LinkedIn, and X --
    see the social-media-growth-manager skill) when present. Older stories generated
    before that field existed fall back to the one generic caption for all four --
    not ideal, but strictly better than an error, and every new story gets the real
    per-platform treatment."""
    s = data["slides"]
    distribution = s.get("distribution")
    if distribution:
        out = {}
        for platform in PLATFORMS:
            entry = distribution.get(platform) or {}
            out[platform] = _combine_caption_and_hashtags(
                strip_markup(entry.get("caption", "")), entry.get("hashtags"),
            )
        if all(out.values()):
            return out
    fallback = build_caption(data)
    return {platform: fallback for platform in PLATFORMS}


def image_files(slug):
    """Stories now render a variable number of slides named "{slug}-{NN}-{kind}.png",
    where a plain filename sort gives the right order. Older stories used a fixed set of
    5 names (cover/backstory/news/why/engage), and a few of the earliest used a flat
    layout with no per-story subfolder at all (e.g. "zepto") -- fall back through both."""
    out_dir = CODE_OUT / slug
    if out_dir.is_dir():
        numbered = sorted(out_dir.glob(f"{slug}-[0-9][0-9]-*.png"))
        if numbered:
            return numbered
        legacy = [f for f in (out_dir / f"{slug}-{k}.png" for k in SLIDE_KINDS) if f.exists()]
        if legacy:
            return legacy
    flat_numbered = sorted(CODE_OUT.glob(f"{slug}-[0-9][0-9]-*.png"))
    if flat_numbered:
        return flat_numbered
    return [f for f in (CODE_OUT / f"{slug}-{k}.png" for k in SLIDE_KINDS) if f.exists()]


def web_path(f):
    """Path to an image file relative to DATA_DIR, for use in a URL served by Flask's
    /assets route. Derived from the actual resolved file rather than re-assuming a
    slug subfolder, since a couple of early stories don't have one (see image_files)."""
    return str(f.relative_to(DATA_DIR))


def prepare(slug, title=None):
    data = find_content_json(slug, title=title)
    imgs = image_files(slug)
    if not imgs:
        raise FileNotFoundError(f"no rendered slide PNGs found for slug '{slug}'")
    return {
        "captions": build_platform_captions(data),
        "images": [web_path(f) for f in imgs],
        "credentials": credentials_status(),
    }


def _check(resp, what):
    if resp.status_code >= 400:
        raise RuntimeError(f"{what} failed ({resp.status_code}): {resp.text[:500]}")
    return resp.json()


def post_to_instagram(slug, base_url, caption, log):
    if not (PAGE_ACCESS_TOKEN and IG_USER_ID):
        raise RuntimeError("Instagram not configured: set META_PAGE_ACCESS_TOKEN and META_IG_USER_ID in .env")
    imgs = image_files(slug)
    child_ids = []
    for f in imgs:
        image_url = f"{base_url.rstrip('/')}/{web_path(f)}"
        log(f"uploading to Instagram: {f.name}")
        resp = requests.post(
            f"{GRAPH_URL}/{IG_USER_ID}/media",
            data={"image_url": image_url, "is_carousel_item": "true", "access_token": PAGE_ACCESS_TOKEN},
            timeout=60,
        )
        body = _check(resp, f"IG media upload ({f.name})")
        child_ids.append(body["id"])

    log("creating Instagram carousel container...")
    resp = requests.post(
        f"{GRAPH_URL}/{IG_USER_ID}/media",
        data={
            "media_type": "CAROUSEL", "caption": caption,
            "children": ",".join(child_ids), "access_token": PAGE_ACCESS_TOKEN,
        },
        timeout=60,
    )
    container = _check(resp, "IG carousel container")

    log("publishing to Instagram...")
    resp = requests.post(
        f"{GRAPH_URL}/{IG_USER_ID}/media_publish",
        data={"creation_id": container["id"], "access_token": PAGE_ACCESS_TOKEN},
        timeout=60,
    )
    published = _check(resp, "IG publish")
    return {"id": published.get("id")}


def post_to_facebook(slug, base_url, caption, log):
    if not (PAGE_ACCESS_TOKEN and PAGE_ID):
        raise RuntimeError("Facebook not configured: set META_PAGE_ACCESS_TOKEN and META_PAGE_ID in .env")
    imgs = image_files(slug)
    media_fbids = []
    for f in imgs:
        image_url = f"{base_url.rstrip('/')}/{web_path(f)}"
        log(f"uploading to Facebook: {f.name}")
        resp = requests.post(
            f"{GRAPH_URL}/{PAGE_ID}/photos",
            data={"url": image_url, "published": "false", "access_token": PAGE_ACCESS_TOKEN},
            timeout=60,
        )
        body = _check(resp, f"FB photo upload ({f.name})")
        media_fbids.append(body["id"])

    log("publishing Facebook post...")
    attached_media = json.dumps([{"media_fbid": mid} for mid in media_fbids])
    resp = requests.post(
        f"{GRAPH_URL}/{PAGE_ID}/feed",
        data={"message": caption, "attached_media": attached_media, "access_token": PAGE_ACCESS_TOKEN},
        timeout=60,
    )
    published = _check(resp, "FB publish")
    return {"id": published.get("id")}


def publish(slug, base_url, targets, captions, log=print):
    """`captions`: dict of platform -> caption text (see build_platform_captions) --
    Instagram and Facebook each post with their OWN platform-native caption, not one
    shared string, since the two perform differently written the same way (see the
    social-media-growth-manager skill: Facebook ranks on reply-generating questions and
    barely uses hashtags, Instagram leans on searchable text and 3-6 focused hashtags)."""
    results = {}
    if "instagram" in targets:
        results["instagram"] = post_to_instagram(slug, base_url, captions.get("instagram", ""), log)
        log("Instagram: published")
    if "facebook" in targets:
        results["facebook"] = post_to_facebook(slug, base_url, captions.get("facebook", ""), log)
        log("Facebook: published")
    return results
